epochs: 10
resume: None
learning_rate: 0.001
weight_decay: 10e-6
inference_device: "cuda"

train:
  s: 1
  batch_size: 8
  num_workers: 4
  valid_size: 0.3
  train_path: "./dataset/train/Colon"

test:
  batch_size: 4
  num_workers: 4
  test_path: "./dataset/test/Colon"

model:
  base_model: "resnet34"